<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>facility_soul_cura</name>
   <tag></tag>
   <elementGuidId>4d25beb5-fdc3-4b58-9dd0-a575770ae89c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>Seoul CURA Healthcare Center</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>d92c10c0-0866-456f-bc8a-89c9aacd220c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1718488092240</value>
      <webElementGuid>44cb1098-2c51-4719-9479-061dc11eb22e</webElementGuid>
   </webElementProperties>
</WebElementEntity>
