<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>facility_tokyo_cura</name>
   <tag></tag>
   <elementGuidId>7d462e0f-0bcf-43f8-b20c-b137925b74b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//option[@value='Tokyo CURA Healthcare Center']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>c8eec9d2-44b2-4e11-a55d-f8c5c1226c58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1718488028813</value>
      <webElementGuid>c95278d5-2ae0-410f-ba9b-88ee806e0691</webElementGuid>
   </webElementProperties>
</WebElementEntity>
