<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>facility_hongkong_cura</name>
   <tag></tag>
   <elementGuidId>4e075f8e-c065-41fd-b780-5e3e8888b7fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//option[@value='Hongkong CURA Healthcare Center']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>0f8cfbea-22a1-4a32-a958-9f5df4579f70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1718488061971</value>
      <webElementGuid>1ac43da6-db01-470b-8cd2-0843c9589e32</webElementGuid>
   </webElementProperties>
</WebElementEntity>
